Adapted Russian translation
AvantTeam/ProjectUnityPublic pull request #7
Opened 2022-01-28 00:11 UTC by lordReddx

##### not machine translation, with love

2022-03-01 10:30 UTC, AzhurniyBaklan requested changes
vanilla - "Ванилла"
Слово "ваниль" в языке есть не просто так.
youngcha - "Янг Ча"
Как у тебя два слога разделились, плюс почему не Янгха, никаких поводов ставить конкретно "ч" нет. Либо без калькирования переводи, либо вообще нет.
small transmission - "малая трансмиссия"
Передача она.
shaft router - "валовой роутер"
Лишний англицизм и несоответсвие базовому переводу, пиши маршрутизатор.
araneidae & theraphosidae - "Арахнид" и "Птицеед"
Анукен своих пауков с латыни калькировал - калькируем и здесь. Аранеид & Ферафосид
modular unit - "Модульный юнит"
Боевая единица.
С вертолётами ещё обговорю с другими моддерами.
part.panel.desc - "Маленькая и плотная бронепластина"
Лучше "малая" и без "и".
tracks-small - "Малый трак"
Во-первых трЭк, во-вторых гусеница.
stattype.weight & stattype.mass - "масса"
В первом случае вес, это другая физическая характеристика.

2022-08-22 18:24 UTC, Xeloboyo approved these changes
seems legit

2022-08-22 18:25 UTC, Xeloboyo commented
Someone who knows russian, can you affirm these translations are accurate?

2023-03-06 09:31 UTC, intrxhyevert commented
одобри пожалуйста

2023-07-17 22:07 UTC, closed without merging