bundle_uk_UA
AvantTeam/ProjectUnityPublic pull request #90
Opened 2023-01-17 14:00 UTC by xStaBUx

**Ukrainian localization of Project Unity** 
_ @Prosta4ok_ua should review_

2023-01-17 14:31 UTC, Prosta4okua requested changes
Ви знаєте як липа шелестить у місячні весняні ночі?

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +mod.contributor = Співавтори
Я чомусь не бачу різниці між Співрозробники / Співавтори

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +mod.contributor = Співавтори
Ось таке знайшов: https://linux.org.ua/index.php?topic=11815.0
але очікую відповідь від досвідченіших перекладачів.

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +mod.disclaimer.text = Цей публічний випуск [accent]Project Unity[] [scarlet]ще не завершений[] та має велику кількість вмісту, який ще належить опублікувати та/або збалансувати, мата цього випуску по
Можливо ліпше версія, а не випуск?
незавершений чому не разом?
Зайвий пробіл перед `Якщо ви зустрінете`

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +item.unity-nickel.details = Невідомо, чому на батьківщині Янгчі так багато нікелю. Існує припущення, що велике зіткнення, у минулому, відірвало велику частину планетарної.
Думаю, що всі коми зайві окрім перед `що`.

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +item.unity-super-alloy.details = Одне з найкращих досягнень фракції, мало хто знає його рецепт і тим більше може його виготовити. Нещодавні дослідження виявили екзотичні властивості матеріалу, вони д
Компа перед `що цей матеріал`.

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +item.unity-sulfur.details = Хоча його складно видобути, його здатність утворювати кислоту цінується тими, хто знає, де і як використовувати цю кислоту.
Сірка вона.

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +block.unity-small-transmission.description = Залежно від сторони входу, пришвидшує або уповільнює обертання. Може знадобитися більше обертової сили для збільшення швидкості.
сповільнює (бо остання голосна)

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +block.unity-torque-source.description = Безперервно генерує обертання. Настроюється. Тільки пісочниця.
Може ліпше налаштовується?

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +block.unity-small-radiator.description = Розсіює тепло
крапка.

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +block.unity-inserter-arm.description = Переміщує та обертає невеликі блоки. \nВи можете побудувати базу разом з ними!
Пробіл зайвий.

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +item.unity-dirium.name = Диріум
Єдиний варіант Дирію. У всіх інших - дірій. Нормалізуй.

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +item.unity-dirium.description = Складний сплав, що складається з багатьох елементів. Чудовий провідник досвіду. Має надприродні властивості, при насиченні досвідом.
Зайва кома остання.  Думаю так краще:
`При насиченні досвідом має надприродні властивості.`

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +liquid.unity-lava.description = Розплавлений камінь, дуже гарячий. Поводьтеся з ним обеережно обережно.
повторення слів

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +block.unity-lava-smelter.details = Ця ітерація плавильного заводу є набагато ефективнішою з невідомих причин. Переважаюча теорія полягає в тому, що те, що ми зараз називаємо «досвідом», насправді бул
Головна замість переважаюча, бо активний дієприкметник.

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +block.unity-dirium-crucible.details = У легендах і стародавніх переказах та неповних перекладах руїн, матеріал "діріум" згадувався як матеріал підставляння, який використовувався у магії. Після незлі
лапки норм зроби

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +block.unity-coal-extractor.description = Добуває вугілля з великої кількості каменю за допомогою води. Він не зазнає шкоди за відсутністю досвіду, але без достатнього досвіду він не видобуває вугілля
Видобуває*

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +block.unity-titanium-extractor.description = Добуває титан зі сталі та щільного сплаву.
Видобуває*

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +block.unity-bt-laser-turret.description =
Лазер типу <<Осколок>> + норм лапки і це до всіх лазерів

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +block.unity-exp-tower.name = Старовинна вежа
tower->башта

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +unit.unity-rpm = об/хв
об/хв -> обертів за хв.
у нас так не можна скорочувати

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +part.root-medium.description = Ядро модульної одиниці. Має більше здоров’я та слотів для зброї, ніж маленьке ядро.
комірок, а не слотів

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +part.root-large.description = Ядро модульної одиниці. Останній рівень ядра. Має більше здоров’я та слотів для зброї, ніж середнє ядро.
комірок, а не слотів

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +part.root-large.description = Ядро модульної одиниці. Останній рівень ядра. Має більше здоров’я та слотів для зброї, ніж середнє ядро.
перед ніж кома не ставиться тут,виправ усюди

```Для виділення порівняльних зворотів, що вводяться словами як, мов, наче, немов, ніби, як і, ніж і т. ін.
Примітка. Не ставиться кома перед як, ніж у виразах (не) більш як, (не) раніше ніж, (не) довше ніж і т. ін.```

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +exp.level.short = Рівень.
short = рів.

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +exp.tooltip = [accent]Блоки з активним рівнем[] взаємодіють з досвідом кулі, вежі та розвантажувачі. Їхній досвід можна вільно транспортувати.\nВикористовуйте стародавні вежі, щоб розподіляти досвід.
розвантажуваач*
башти, а не вежі

2023-01-17 14:31 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +exp.upgradefrom = Покращення від [accent]рівня {0}[] {1}
Upgrade - поліпшення

2023-01-17 14:39 UTC, xStaBUx commented on main/assets/bundles/bundle_uk_UA.properties
> +block.unity-wall-drill.description = Бур, який можна використовувати для видобування руд у стінах... або ворожих одиниць.
ні, він може "видобувати" ворогів

2023-01-17 15:01 UTC, Prosta4okua requested changes

2023-01-17 15:01 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +exp.tooltip = [accent]Блоки з активним рівнем[] взаємодіють з досвідом кулі, башти та розвантажуваач. Їхній досвід можна вільно транспортувати.\nВикористовуйте стародавні башти, щоб розподіляти досві
> розвантажуваач

2023-01-17 15:01 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +block.unity-bt-laser-turret.name = Лазер типу <<Прорив>>
«»

2023-01-17 15:01 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +block.unity-dirium-crucible.details = У легендах і стародавніх переказах та неповних перекладах руїн, матеріал <<діріум>> згадувався як матеріал підставляння, який використовувався у магії. Після нез
«»

2023-01-17 15:01 UTC, xStaBUx commented on main/assets/bundles/bundle_uk_UA.properties
> +exp.tooltip = [accent]Блоки з активним рівнем[] взаємодіють з досвідом кулі, башти та розвантажуваач. Їхній досвід можна вільно транспортувати.\nВикористовуйте стародавні башти, щоб розподіляти досві
?

2023-01-17 15:03 UTC, Prosta4okua commented on main/assets/bundles/bundle_uk_UA.properties
> +exp.tooltip = [accent]Блоки з активним рівнем[] взаємодіють з досвідом кулі, башти та розвантажуваач. Їхній досвід можна вільно транспортувати.\nВикористовуйте стародавні башти, щоб розподіляти досві
подвійне а

2023-01-17 15:11 UTC, xStaBUx commented
Done
@Xeloboyo (?) merge this

2023-01-17 15:15 UTC, Prosta4okua approved these changes

2023-01-17 15:17 UTC, xStaBUx commented
Done 
@Xeloboyo (?) merge this

2023-03-06 09:30 UTC, intrxhyevert commented
спасибо

2023-03-27 13:31 UTC, closed without merging